<?php

namespace App\Services;

use App\Models\InvoicePdf;
use App\Models\InvoiceUnit;
use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Support\Facades\Log;

class InvoicePdfService
{
    public function __construct(
        protected FileStorageService $fileStorage
    ) {
    }

    /**
     * Generate PDF from HTML and store it (overwrites existing).
     */
    public function generatePdf(InvoiceUnit $invoice, string $html, int $generatedBy): InvoicePdf
    {
        Log::info('Generating PDF for Invoice ID: ' . $invoice->id);
        Log::info('Generated By: ' . $generatedBy);
        
        // Generate filename
        $filename = $this->generateFilename($invoice->invoice_number);
        
        // Load existing PDF record if it exists
        $existingPdf = InvoicePdf::where('invoice_unit_id', $invoice->id)
            ->where('is_latest', true)
            ->first();
        
        // Generate PDF from HTML
        $pdf = Pdf::loadHTML($html);
        $pdf->setPaper('A4', 'portrait');
        
        // Get PDF content
        $pdfContent = $pdf->output();
        
        // Store PDF file (will overwrite if exists)
        $filePath = $this->storePdfFile($filename, $pdfContent);
        
        // Create or update database record (keep same id)
        if ($existingPdf) {
            $existingPdf->update([
                'file_name' => $filename,
                'file_path' => $filePath,
                'file_size' => strlen($pdfContent),
                'is_latest' => true,
                'generated_by' => $generatedBy,
            ]);
            $invoicePdf = $existingPdf;
        } else {
            $invoicePdf = InvoicePdf::create([
                'invoice_unit_id' => $invoice->id,
                'version' => 1,
                'file_name' => $filename,
                'file_path' => $filePath,
                'file_size' => strlen($pdfContent),
                'is_latest' => true,
                'generated_by' => $generatedBy,
            ]);
        }
        
        return $invoicePdf;
    }
    
    /**
     * Generate filename for the PDF.
     */
    private function generateFilename(string $invoiceNumber): string
    {
        return $invoiceNumber . '.pdf';
    }
    
    /**
     * Store PDF file in storage.
     */
    private function storePdfFile(string $filename, string $content): string
    {
        $filePath = "invoice-pdfs/{$filename}";
        
        // Create directory if it doesn't exist (for local storage)
        $dir = dirname($filePath);
        $this->fileStorage->makeDirectory($dir);
        
        // Store the file (will overwrite if exists)
        $this->fileStorage->store($filePath, $content);
        
        return $filePath;
    }
    
    /**
     * Get the latest PDF for an invoice.
     */
    public function getLatestPdf(InvoiceUnit $invoice): ?InvoicePdf
    {
        return InvoicePdf::where('invoice_unit_id', $invoice->id)
            ->where('is_latest', true)
            ->latest()
            ->first();
    }
    
    /**
     * Delete all PDFs for an invoice.
     */
    public function deleteAllPdfs(InvoiceUnit $invoice): void
    {
        $pdfs = InvoicePdf::where('invoice_unit_id', $invoice->id)->get();
        
        foreach ($pdfs as $pdf) {
            // Delete file from storage
            $this->fileStorage->delete($pdf->file_path);
            
            // Delete database record
            $pdf->delete();
        }
    }
    
    /**
     * Get PDF file content for download.
     */
    public function getPdfContent(InvoicePdf $invoicePdf): ?string
    {
        return $this->fileStorage->get($invoicePdf->file_path);
    }
}
