[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
  "cp railway.env.example .env || cp .env.example .env",
  "mkdir -p bootstrap/cache storage/app storage/framework/cache storage/framework/sessions storage/framework/views storage/logs",
  "chmod -R 777 bootstrap storage"
]

[start]
cmd = "./start.sh"
